---
- import_playbook: provision.yml
- import_playbook: docker.yml
- import_playbook: jenkins.yml
- import_playbook: sonarqube.yml
- import_playbook: nexus.yml
- import_playbook: monitoring.yml
- import_playbook: kubernetes.yml
