#!/bin/bash

# 1. Determine the absolute root directory of the project
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" & pwd -P)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." & pwd -P)"

# 2. Define absolute paths (No more ../../../ errors!)
TF_DIR="${PROJECT_ROOT}/terraform/envs/dev"
INVENTORY_FILE="${PROJECT_ROOT}/ansible/inventory/aws.ini"
KEY_PATH="${TF_DIR}/devops-aws-key.pem"

# 3. Go to the terraform folder to run terraform output
cd "$TF_DIR" || exit 1

# 4. Get the IPs from Terraform
echo "Fetching IP addresses from Terraform..."
CONTROL_IP=$(terraform output -raw control_plane_public_ip)
K8S_MASTER_IP=$(terraform output -raw k8s_master_public_ip)
MONITORING_IP=$(terraform output -raw monitoring_ops_public_ip)
K8S_WORKER_IPS=$(terraform output -json k8s_workers_public_ips | jq -r '.[]')

# 5. Create the inventory file
echo "Generating Ansible inventory at: $INVENTORY_FILE"
cat <<EOF > "$INVENTORY_FILE"
# This file was automatically generated by generate-ansible-inventory.sh
# Do not edit manually!

[control_plane]
control-node ansible_host=$CONTROL_IP ansible_user=ubuntu ansible_ssh_private_key_file=$KEY_PATH

[k8s_master]
k8s-master ansible_host=$K8S_MASTER_IP ansible_user=ubuntu ansible_ssh_private_key_file=$KEY_PATH

[k8s_workers]
EOF

# Loop through worker IPs
i=1
for IP in $K8S_WORKER_IPS; do
    echo "k8s-worker$i ansible_host=$IP ansible_user=ubuntu ansible_ssh_private_key_file=$KEY_PATH" >> "$INVENTORY_FILE"
    i=$((i+1))
done

cat <<EOF >> "$INVENTORY_FILE"

[monitoring_ops]
monitoring-node ansible_host=$MONITORING_IP ansible_user=ubuntu ansible_ssh_private_key_file=$KEY_PATH

[all:children]
control_plane
k8s_master
k8s_workers
monitoring_ops
EOF

echo "Done! Inventory created successfully."
